# Source: home-assistant/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tisdif-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: tisdif
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
---
# Source: home-assistant/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tisdif-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: tisdif
spec:
  type: NodePort
  publishNotReadyAddresses: false
  ports:
    - name: api
      port: 8123
      protocol: TCP
      targetPort: 8123

    - name: configurator
      port: 3218
      protocol: TCP
      targetPort: 3218

  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: tisdif
---
# Source: home-assistant/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tisdif-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: tisdif
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: tisdif
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: tisdif
    spec:
      initContainers:
      containers:
        - name: home-assistant
          image: "homeassistant/home-assistant:0.112.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: api
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          env:
          envFrom:
          volumeMounts:
            - mountPath: /config
              name: config
          securityContext:
            runAsUser: 0
          resources: {}
        - name: configurator
          image: "causticlab/hass-configurator-docker:0.3.5-x86_64"
          imagePullPolicy: IfNotPresent
          ports:
            - name: configurator
              containerPort: 3218
              protocol: TCP
          env:
            - name: HC_HASS_API
              value: "http://127.0.0.1:8123/api/"
            - name: HC_BASEPATH
              value: "/config"
            - name: HC_ENFORCE_BASEPATH
              value: "true"
          volumeMounts:
            - mountPath: /config
              name: config
          securityContext:
            runAsUser: 0
          resources: null
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tisdif-home-assistant
---
# Source: home-assistant/templates/secret.yaml
---

---
# Source: home-assistant/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tisdif-home-assistant-prometheus-exporter
spec:
  endpoints:
    - targetPort: api
      path: /api/prometheus
  jobLabel: tisdif-home-assistant-prometheus-exporter
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: tisdif
